import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const breeder = await prisma.Breeder.createMany({
    data: [
      {
        firstName: "Alissa",
        lastName: "Chellam",
        email: "achellam0@fda.gov",
        password: "p7SaX6LfIdu",
        phoneNumber: "823-362-9564",
        address: "48362 Moulton Lane",
        profileImage: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
        revenue: 200,
      },
      {
        firstName: "Alyce",
        lastName: "Calendar",
        email: "acalendar1@nature.com",
        password: "HwgGPRIWLV",
        phoneNumber: "978-414-4750",
        address: "739 Mccormick Pass",
        profileImage: "http://dummyimage.com/241x100.png/5fa2dd/ffffff",
        revenue: 2000,
      },
      {
        firstName: "Jacquie",
        lastName: "Burrel",
        email: "jburrel2@naver.com",
        password: "n01PP2W",
        phoneNumber: "179-475-1054",
        address: "0871 Namekagon Crossing",
        profileImage: "http://dummyimage.com/218x100.png/ff4444/ffffff",
        revenue: 200,
      },
      {
        firstName: "Tish",
        lastName: "Shailer",
        email: "tshailer3@time.com",
        password: "TTqTdQY24mJc",
        phoneNumber: "840-211-2136",
        address: "15 Mesta Trail",
        profileImage: "http://dummyimage.com/236x100.png/ff4444/ffffff",
        revenue: 1500,
      },
      {
        firstName: "Giulia",
        lastName: "Speechley",
        email: "gspeechley4@abc.net.au",
        password: "uZX5xF8KK",
        phoneNumber: "509-121-2055",
        address: "8 Kennedy Point",
        profileImage: "http://dummyimage.com/150x100.png/cc0000/ffffff",
        revenue: 2000,
      },
      {
        firstName: "Lewiss",
        lastName: "Rapaport",
        email: "lrapaport5@elegantthemes.com",
        password: "8iKdAc2syY",
        phoneNumber: "413-432-0501",
        address: "033 Huxley Park",
        profileImage: "http://dummyimage.com/105x100.png/5fa2dd/ffffff",
        revenue: 250,
      },
      {
        firstName: "Layla",
        lastName: "Greenin",
        email: "lgreenin6@elegantthemes.com",
        password: "FYCfU9TE",
        phoneNumber: "277-135-7213",
        address: "559 Lillian Way",
        profileImage: "http://dummyimage.com/250x100.png/ff4444/ffffff",
        revenue: 400,
      },
      {
        firstName: "Rufus",
        lastName: "Aucock",
        email: "raucock7@addtoany.com",
        password: "BQ0quL0",
        phoneNumber: "920-241-5615",
        address: "2 Birchwood Place",
        profileImage: "http://dummyimage.com/152x100.png/cc0000/ffffff",
        revenue: 5000,
      },
      {
        firstName: "Linus",
        lastName: "Tomet",
        email: "ltomet8@theglobeandmail.com",
        password: "VauYQsS",
        phoneNumber: "220-336-6344",
        address: "255 Warner Trail",
        profileImage: "http://dummyimage.com/197x100.png/dddddd/000000",
        revenue: 100,
      },
      {
        firstName: "Abbye",
        lastName: "De Benedetti",
        email: "adebenedetti9@creativecommons.org",
        password: "BtBkvgYPq",
        phoneNumber: "577-581-6782",
        address: "0055 Corry Plaza",
        profileImage: "http://dummyimage.com/113x100.png/ff4444/ffffff",
        revenue: 350,
      },
      {
        firstName: "Etti",
        lastName: "Maden",
        email: "emadena@behance.net",
        password: "mIyr8nkJ",
        phoneNumber: "413-139-5976",
        address: "66514 Milwaukee Road",
        profileImage: "http://dummyimage.com/183x100.png/dddddd/000000",
        revenue: 350,
      },
      {
        firstName: "Larissa",
        lastName: "Betchley",
        email: "lbetchleyb@tinyurl.com",
        password: "iqEAkjNq5B",
        phoneNumber: "851-479-8377",
        address: "8595 Arapahoe Point",
        profileImage: "http://dummyimage.com/134x100.png/cc0000/ffffff",
        revenue: 5000,
      },
      {
        firstName: "Alfy",
        lastName: "Breinlein",
        email: "abreinleinc@mapquest.com",
        password: "F2eftKN35Jio",
        phoneNumber: "222-457-2815",
        address: "569 Gale Avenue",
        profileImage: "http://dummyimage.com/194x100.png/dddddd/000000",
        revenue: 5000,
      },
      {
        firstName: "Eulalie",
        lastName: "Jimmison",
        email: "ejimmisond@bizjournals.com",
        password: "0zgI02IL8k",
        phoneNumber: "459-922-3513",
        address: "57 Amoth Circle",
        profileImage: "http://dummyimage.com/196x100.png/ff4444/ffffff",
        revenue: 0,
      },
      {
        firstName: "Welsh",
        lastName: "Cross",
        email: "wcrosse@answers.com",
        password: "pAEYWQiB",
        phoneNumber: "648-349-4458",
        address: "02 Grasskamp Court",
        profileImage: "http://dummyimage.com/235x100.png/ff4444/ffffff",
        revenue: 1500,
      },
      {
        firstName: "Dimitry",
        lastName: "Strowger",
        email: "dstrowgerf@ocn.ne.jp",
        password: "dx3iB8H9Np",
        phoneNumber: "503-564-0995",
        address: "075 Evergreen Trail",
        profileImage: "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
        revenue: 250,
      },
      {
        firstName: "Delly",
        lastName: "Rawes",
        email: "drawesg@europa.eu",
        password: "tNQtID4MKZZ",
        phoneNumber: "362-481-0332",
        address: "2233 Utah Court",
        profileImage: "http://dummyimage.com/163x100.png/dddddd/000000",
        revenue: 200,
      },
      {
        firstName: "Hailee",
        lastName: "Bugden",
        email: "hbugdenh@redcross.org",
        password: "71kryeebBt",
        phoneNumber: "407-167-9556",
        address: "9685 Gerald Pass",
        profileImage: "http://dummyimage.com/153x100.png/dddddd/000000",
        revenue: 350,
      },
      {
        firstName: "Gene",
        lastName: "Jenner",
        email: "gjenneri@cyberchimps.com",
        password: "cjtzY3",
        phoneNumber: "106-290-1834",
        address: "52688 Bobwhite Court",
        profileImage: "http://dummyimage.com/183x100.png/ff4444/ffffff",
        revenue: 1000,
      },
      {
        firstName: "Garek",
        lastName: "McClory",
        email: "gmccloryj@adobe.com",
        password: "842b0Hm9",
        phoneNumber: "395-526-0033",
        address: "5754 Shopko Circle",
        profileImage: "http://dummyimage.com/141x100.png/cc0000/ffffff",
        revenue: 300,
      },
      {
        firstName: "Glyn",
        lastName: "Dimnage",
        email: "gdimnagek@usa.gov",
        password: "owayThFhl",
        phoneNumber: "868-587-9652",
        address: "8815 Nobel Hill",
        profileImage: "http://dummyimage.com/209x100.png/ff4444/ffffff",
        revenue: 2000,
      },
      {
        firstName: "Jess",
        lastName: "Climo",
        email: "jclimol@slate.com",
        password: "GhXIne904orG",
        phoneNumber: "679-362-0393",
        address: "156 Ridge Oak Drive",
        profileImage: "http://dummyimage.com/202x100.png/ff4444/ffffff",
        revenue: 5000,
      },
      {
        firstName: "Gustavo",
        lastName: "Glaserman",
        email: "gglasermanm@dailymail.co.uk",
        password: "CH8mjgE2om",
        phoneNumber: "886-625-6372",
        address: "71 Eagle Crest Drive",
        profileImage: "http://dummyimage.com/183x100.png/dddddd/000000",
        revenue: 400,
      },
      {
        firstName: "Didi",
        lastName: "Bastin",
        email: "dbastinn@wikipedia.org",
        password: "N5wef70qBF",
        phoneNumber: "194-394-0397",
        address: "75540 Longview Lane",
        profileImage: "http://dummyimage.com/130x100.png/cc0000/ffffff",
        revenue: 1500,
      },
      {
        firstName: "Robbert",
        lastName: "Wigelsworth",
        email: "rwigelswortho@psu.edu",
        password: "H2HqbuoS135g",
        phoneNumber: "401-884-5285",
        address: "60513 Hoepker Way",
        profileImage: "http://dummyimage.com/103x100.png/ff4444/ffffff",
        revenue: 200,
      },
      {
        firstName: "Dougy",
        lastName: "Tregunnah",
        email: "dtregunnahp@stumbleupon.com",
        password: "uidIWZ",
        phoneNumber: "756-360-2978",
        address: "230 Steensland Avenue",
        profileImage: "http://dummyimage.com/229x100.png/cc0000/ffffff",
        revenue: 5000,
      },
      {
        firstName: "Betsey",
        lastName: "Earley",
        email: "bearleyq@is.gd",
        password: "GXpgXtmE",
        phoneNumber: "374-894-3939",
        address: "238 Iowa Road",
        profileImage: "http://dummyimage.com/109x100.png/5fa2dd/ffffff",
        revenue: 100,
      },
      {
        firstName: "Renell",
        lastName: "De Castri",
        email: "rdecastrir@twitpic.com",
        password: "3vd9V2",
        phoneNumber: "308-681-9724",
        address: "02602 Barnett Trail",
        profileImage: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
        revenue: 400,
      },
      {
        firstName: "Shawn",
        lastName: "Gavozzi",
        email: "sgavozzis@instagram.com",
        password: "XpcRP5k",
        phoneNumber: "937-190-0037",
        address: "5989 Warner Lane",
        profileImage: "http://dummyimage.com/175x100.png/cc0000/ffffff",
        revenue: 1500,
      },
      {
        firstName: "Martelle",
        lastName: "Dunstall",
        email: "mdunstallt@parallels.com",
        password: "joUd38FV",
        phoneNumber: "170-201-7852",
        address: "49 Mayer Road",
        profileImage: "http://dummyimage.com/190x100.png/5fa2dd/ffffff",
        revenue: 250,
      },
      {
        firstName: "Ania",
        lastName: "Scolland",
        email: "ascollandu@phoca.cz",
        password: "HupJHEmMuyys",
        phoneNumber: "516-253-8860",
        address: "69 David Lane",
        profileImage: "http://dummyimage.com/216x100.png/cc0000/ffffff",
        revenue: 400,
      },
      {
        firstName: "Bartlet",
        lastName: "Bradane",
        email: "bbradanev@bing.com",
        password: "Ep02GTEeZtmO",
        phoneNumber: "155-981-1300",
        address: "87 Maywood Avenue",
        profileImage: "http://dummyimage.com/159x100.png/dddddd/000000",
        revenue: 250,
      },
      {
        firstName: "Finlay",
        lastName: "Pridmore",
        email: "fpridmorew@pcworld.com",
        password: "hImSxYgu6N",
        phoneNumber: "350-365-6856",
        address: "14 Loomis Court",
        profileImage: "http://dummyimage.com/149x100.png/ff4444/ffffff",
        revenue: 350,
      },
      {
        firstName: "Dennet",
        lastName: "Brazier",
        email: "dbrazierx@vistaprint.com",
        password: "c5zlCKo",
        phoneNumber: "163-219-2033",
        address: "64475 Graedel Junction",
        profileImage: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
        revenue: 0,
      },
      {
        firstName: "Staford",
        lastName: "Dundon",
        email: "sdundony@simplemachines.org",
        password: "08PWTTwYbaY",
        phoneNumber: "212-320-0980",
        address: "0927 Shasta Junction",
        profileImage: "http://dummyimage.com/187x100.png/cc0000/ffffff",
        revenue: 400,
      },
      {
        firstName: "Waverly",
        lastName: "Romi",
        email: "wromiz@last.fm",
        password: "O5xS4ERiY9c",
        phoneNumber: "497-341-9702",
        address: "748 Crest Line Plaza",
        profileImage: "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
        revenue: 300,
      },
      {
        firstName: "Lionello",
        lastName: "Tarburn",
        email: "ltarburn10@reuters.com",
        password: "87xdqJ8c",
        phoneNumber: "750-708-9726",
        address: "2 Elgar Lane",
        profileImage: "http://dummyimage.com/159x100.png/dddddd/000000",
        revenue: 200,
      },
      {
        firstName: "Taryn",
        lastName: "Jedrys",
        email: "tjedrys11@slate.com",
        password: "RfsqJ3",
        phoneNumber: "515-451-8271",
        address: "0677 Bunting Street",
        profileImage: "http://dummyimage.com/119x100.png/ff4444/ffffff",
        revenue: 50,
      },
      {
        firstName: "Eba",
        lastName: "Wragg",
        email: "ewragg12@mozilla.org",
        password: "7RxMNIuM",
        phoneNumber: "429-370-8714",
        address: "8934 Lawn Drive",
        profileImage: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
        revenue: 50,
      },
      {
        firstName: "Wilhelmina",
        lastName: "Weeke",
        email: "wweeke13@so-net.ne.jp",
        password: "u3gJ4oET",
        phoneNumber: "699-819-8795",
        address: "5841 Darwin Street",
        profileImage: "http://dummyimage.com/156x100.png/ff4444/ffffff",
        revenue: 1500,
      },
      {
        firstName: "Corinne",
        lastName: "Giuron",
        email: "cgiuron14@princeton.edu",
        password: "5SO2V6lQ",
        phoneNumber: "726-815-7837",
        address: "2740 Sauthoff Terrace",
        profileImage: "http://dummyimage.com/118x100.png/5fa2dd/ffffff",
        revenue: 250,
      },
      {
        firstName: "Nita",
        lastName: "Wendover",
        email: "nwendover15@ezinearticles.com",
        password: "VyTfXWnNhmo4",
        phoneNumber: "771-929-1863",
        address: "66 Maryland Drive",
        profileImage: "http://dummyimage.com/212x100.png/5fa2dd/ffffff",
        revenue: 5000,
      },
      {
        firstName: "Athena",
        lastName: "Kettell",
        email: "akettell16@reverbnation.com",
        password: "dE4aZKA",
        phoneNumber: "515-906-2852",
        address: "89 Briar Crest Trail",
        profileImage: "http://dummyimage.com/245x100.png/dddddd/000000",
        revenue: 350,
      },
      {
        firstName: "Hedi",
        lastName: "Benneton",
        email: "hbenneton17@seesaa.net",
        password: "R2EHY8R8RP9r",
        phoneNumber: "441-144-2020",
        address: "155 Bunting Parkway",
        profileImage: "http://dummyimage.com/174x100.png/ff4444/ffffff",
        revenue: 200,
      },
      {
        firstName: "Zonda",
        lastName: "Buchett",
        email: "zbuchett18@etsy.com",
        password: "yMIiRaszbFb",
        phoneNumber: "456-825-0741",
        address: "9 Lien Road",
        profileImage: "http://dummyimage.com/206x100.png/dddddd/000000",
        revenue: 1500,
      },
      {
        firstName: "Ertha",
        lastName: "Collen",
        email: "ecollen19@jiathis.com",
        password: "iMXvYTJ1q",
        phoneNumber: "482-393-0148",
        address: "8 North Place",
        profileImage: "http://dummyimage.com/180x100.png/cc0000/ffffff",
        revenue: 100,
      },
      {
        firstName: "Tessi",
        lastName: "Millership",
        email: "tmillership1a@clickbank.net",
        password: "sV3VtzGwg",
        phoneNumber: "909-126-9061",
        address: "26999 Prentice Point",
        profileImage: "http://dummyimage.com/149x100.png/cc0000/ffffff",
        revenue: 2000,
      },
      {
        firstName: "Alysa",
        lastName: "Letch",
        email: "aletch1b@tinyurl.com",
        password: "paJzinE88hN4",
        phoneNumber: "961-891-1338",
        address: "60002 Tomscot Alley",
        profileImage: "http://dummyimage.com/196x100.png/ff4444/ffffff",
        revenue: 0,
      },
      {
        firstName: "Davide",
        lastName: "McMychem",
        email: "dmcmychem1c@cafepress.com",
        password: "ORUWkFb",
        phoneNumber: "464-728-1415",
        address: "2839 7th Crossing",
        profileImage: "http://dummyimage.com/159x100.png/ff4444/ffffff",
        revenue: 200,
      },
      {
        firstName: "Matthiew",
        lastName: "Housegoe",
        email: "mhousegoe1d@fastcompany.com",
        password: "nDrO2aFtTzf",
        phoneNumber: "229-549-6130",
        address: "4169 Drewry Way",
        profileImage: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
        revenue: 0,
      },
    ],
  });

  const pet = await prisma.pet.createMany({
    data: [
      {
        name: "Jaeger, long-tailed",
        dateOfBirth: "6/17/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/108x100.png/cc0000/ffffff",
        price: 200,
        gender: "Female",
        breederId: 7,
      },
      {
        name: "African bush squirrel",
        dateOfBirth: "11/5/2021",
        description: "Crazy",
        profileImage: "http://dummyimage.com/196x100.png/5fa2dd/ffffff",
        price: 3000,
        gender: "Female",
        breederId: 6,
      },
      {
        name: "Great white pelican",
        dateOfBirth: "10/29/2021",
        description: "Protector",
        profileImage: "http://dummyimage.com/249x100.png/dddddd/000000",
        price: 1800,
        gender: "Male",
        breederId: 7,
      },
      {
        name: "Numbat",
        dateOfBirth: "8/22/2022",
        description: "Aggressive",
        profileImage: "http://dummyimage.com/219x100.png/5fa2dd/ffffff",
        price: 350,
        gender: "Female",
        breederId: 5,
      },
      {
        name: "Koala",
        dateOfBirth: "10/22/2021",
        description: "Caring",
        profileImage: "http://dummyimage.com/187x100.png/5fa2dd/ffffff",
        price: 500,
        gender: "Male",
        breederId: 9,
      },
      {
        name: "Marten, american",
        dateOfBirth: "3/13/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/164x100.png/dddddd/000000",
        price: 250,
        gender: "Female",
        breederId: 3,
      },
      {
        name: "African porcupine",
        dateOfBirth: "8/2/2022",
        description: "Scared",
        profileImage: "http://dummyimage.com/222x100.png/ff4444/ffffff",
        price: 3000,
        gender: "Female",
        breederId: 6,
      },
      {
        name: "White-browed sparrow weaver",
        dateOfBirth: "7/22/2022",
        description: "Energetic",
        profileImage: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
        price: 1000,
        gender: "Male",
        breederId: 6,
      },
      {
        name: "White-necked raven",
        dateOfBirth: "10/17/2021",
        description: "Hyper",
        profileImage: "http://dummyimage.com/163x100.png/cc0000/ffffff",
        price: 350,
        gender: "Female",
        breederId: 9,
      },
      {
        name: "Toucan, white-throated",
        dateOfBirth: "8/26/2022",
        description: "Crazy",
        profileImage: "http://dummyimage.com/186x100.png/dddddd/000000",
        price: 100,
        gender: "Male",
        breederId: 8,
      },
      {
        name: "Bat, madagascar fruit",
        dateOfBirth: "6/20/2022",
        description: "Scared",
        profileImage: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
        price: 4000,
        gender: "Female",
        breederId: 1,
      },
      {
        name: "Large-eared bushbaby",
        dateOfBirth: "2/19/2022",
        description: "Shy",
        profileImage: "http://dummyimage.com/154x100.png/5fa2dd/ffffff",
        price: 2000,
        gender: "Male",
        breederId: 5,
      },
      {
        name: "Kookaburra, laughing",
        dateOfBirth: "11/21/2021",
        description: "Aggressive",
        profileImage: "http://dummyimage.com/229x100.png/dddddd/000000",
        price: 100,
        gender: "Female",
        breederId: 8,
      },
      {
        name: "Monster, gila",
        dateOfBirth: "6/19/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/171x100.png/cc0000/ffffff",
        price: 100,
        gender: "Female",
        breederId: 5,
      },
      {
        name: "Iguana, common green",
        dateOfBirth: "6/5/2022",
        description: "Protector",
        profileImage: "http://dummyimage.com/145x100.png/ff4444/ffffff",
        price: 200,
        gender: "Female",
        breederId: 8,
      },
      {
        name: "Phascogale, brush-tailed",
        dateOfBirth: "2/13/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/227x100.png/dddddd/000000",
        price: 100,
        gender: "Female",
        breederId: 6,
      },
      {
        name: "Red sheep",
        dateOfBirth: "5/30/2022",
        description: "Hyper",
        profileImage: "http://dummyimage.com/234x100.png/ff4444/ffffff",
        price: 2000,
        gender: "Female",
        breederId: 5,
      },
      {
        name: "Marine iguana",
        dateOfBirth: "2/25/2022",
        description: "Shy",
        profileImage: "http://dummyimage.com/197x100.png/ff4444/ffffff",
        price: 350,
        gender: "Male",
        breederId: 1,
      },
      {
        name: "Gray duiker",
        dateOfBirth: "11/24/2021",
        description: "Crazy",
        profileImage: "http://dummyimage.com/116x100.png/dddddd/000000",
        price: 100,
        gender: "Female",
        breederId: 2,
      },
      {
        name: "Blackbird, red-winged",
        dateOfBirth: "5/31/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/215x100.png/cc0000/ffffff",
        price: 500,
        gender: "Female",
        breederId: 10,
      },
      {
        name: "White-throated kingfisher",
        dateOfBirth: "1/17/2022",
        description: "Fun",
        profileImage: "http://dummyimage.com/109x100.png/5fa2dd/ffffff",
        price: 400,
        gender: "Female",
        breederId: 9,
      },
      {
        name: "Woolly-necked stork",
        dateOfBirth: "4/2/2022",
        description: "Caring",
        profileImage: "http://dummyimage.com/200x100.png/ff4444/ffffff",
        price: 400,
        gender: "Female",
        breederId: 6,
      },
      {
        name: "Cobra, cape",
        dateOfBirth: "12/29/2021",
        description: "Crazy",
        profileImage: "http://dummyimage.com/137x100.png/cc0000/ffffff",
        price: 3000,
        gender: "Male",
        breederId: 4,
      },
      {
        name: "Grey lourie",
        dateOfBirth: "2/18/2022",
        description: "Crazy",
        profileImage: "http://dummyimage.com/234x100.png/dddddd/000000",
        price: 250,
        gender: "Female",
        breederId: 10,
      },
      {
        name: "Heron, giant",
        dateOfBirth: "9/24/2021",
        description: "Hyper",
        profileImage: "http://dummyimage.com/151x100.png/cc0000/ffffff",
        price: 250,
        gender: "Male",
        breederId: 2,
      },
      {
        name: "Thirteen-lined squirrel",
        dateOfBirth: "12/25/2021",
        description: "Hyper",
        profileImage: "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
        price: 300,
        gender: "Male",
        breederId: 8,
      },
      {
        name: "Cockatoo, slender-billed",
        dateOfBirth: "8/14/2022",
        description: "Aggressive",
        profileImage: "http://dummyimage.com/228x100.png/ff4444/ffffff",
        price: 1500,
        gender: "Male",
        breederId: 10,
      },
      {
        name: "Genet, common",
        dateOfBirth: "9/26/2021",
        description: "Shy",
        profileImage: "http://dummyimage.com/124x100.png/ff4444/ffffff",
        price: 200,
        gender: "Male",
        breederId: 6,
      },
      {
        name: "Genet, small-spotted",
        dateOfBirth: "12/15/2021",
        description: "Funny",
        profileImage: "http://dummyimage.com/105x100.png/dddddd/000000",
        price: 3000,
        gender: "Male",
        breederId: 7,
      },
      {
        name: "Bennett's wallaby",
        dateOfBirth: "9/20/2021",
        description: "Caring",
        profileImage: "http://dummyimage.com/120x100.png/cc0000/ffffff",
        price: 500,
        gender: "Male",
        breederId: 8,
      },
      {
        name: "Sulfur-crested cockatoo",
        dateOfBirth: "5/13/2022",
        description: "Funny",
        profileImage: "http://dummyimage.com/105x100.png/ff4444/ffffff",
        price: 1500,
        gender: "Female",
        breederId: 10,
      },
      {
        name: "American bison",
        dateOfBirth: "5/16/2022",
        description: "Protector",
        profileImage: "http://dummyimage.com/153x100.png/ff4444/ffffff",
        price: 250,
        gender: "Female",
        breederId: 7,
      },
      {
        name: "Orca",
        dateOfBirth: "4/10/2022",
        description: "Funny",
        profileImage: "http://dummyimage.com/235x100.png/ff4444/ffffff",
        price: 4000,
        gender: "Female",
        breederId: 1,
      },
      {
        name: "Robin, white-throated",
        dateOfBirth: "6/4/2022",
        description: "Shy",
        profileImage: "http://dummyimage.com/216x100.png/5fa2dd/ffffff",
        price: 2000,
        gender: "Male",
        breederId: 8,
      },
      {
        name: "Capuchin, black-capped",
        dateOfBirth: "3/19/2022",
        description: "Funny",
        profileImage: "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        price: 1800,
        gender: "Female",
        breederId: 2,
      },
      {
        name: "Dove, little brown",
        dateOfBirth: "3/8/2022",
        description: "Crazy",
        profileImage: "http://dummyimage.com/133x100.png/5fa2dd/ffffff",
        price: 1000,
        gender: "Female",
        breederId: 8,
      },
      {
        name: "Black-capped capuchin",
        dateOfBirth: "4/14/2022",
        description: "Hyper",
        profileImage: "http://dummyimage.com/157x100.png/cc0000/ffffff",
        price: 1000,
        gender: "Male",
        breederId: 1,
      },
      {
        name: "Common raccoon",
        dateOfBirth: "8/19/2022",
        description: "Energetic",
        profileImage: "http://dummyimage.com/147x100.png/cc0000/ffffff",
        price: 350,
        gender: "Male",
        breederId: 2,
      },
      {
        name: "Lemur, grey mouse",
        dateOfBirth: "1/31/2022",
        description: "Scared",
        profileImage: "http://dummyimage.com/106x100.png/5fa2dd/ffffff",
        price: 3000,
        gender: "Male",
        breederId: 7,
      },
      {
        name: "Cockatoo, long-billed",
        dateOfBirth: "5/28/2022",
        description: "Crazy",
        profileImage: "http://dummyimage.com/163x100.png/5fa2dd/ffffff",
        price: 400,
        gender: "Female",
        breederId: 8,
      },
      {
        name: "Long-finned pilot whale",
        dateOfBirth: "7/29/2022",
        description: "Scared",
        profileImage: "http://dummyimage.com/131x100.png/cc0000/ffffff",
        price: 3000,
        gender: "Male",
        breederId: 8,
      },
      {
        name: "African buffalo",
        dateOfBirth: "4/17/2022",
        description: "Shy",
        profileImage: "http://dummyimage.com/235x100.png/dddddd/000000",
        price: 100,
        gender: "Female",
        breederId: 5,
      },
      {
        name: "Macaque, bonnet",
        dateOfBirth: "8/4/2022",
        description: "Aggressive",
        profileImage: "http://dummyimage.com/142x100.png/dddddd/000000",
        price: 1800,
        gender: "Male",
        breederId: 2,
      },
      {
        name: "Bustard, denham's",
        dateOfBirth: "11/18/2021",
        description: "Shy",
        profileImage: "http://dummyimage.com/224x100.png/ff4444/ffffff",
        price: 250,
        gender: "Female",
        breederId: 9,
      },
      {
        name: "Dassie",
        dateOfBirth: "7/29/2022",
        description: "Shy",
        profileImage: "http://dummyimage.com/188x100.png/ff4444/ffffff",
        price: 1000,
        gender: "Male",
        breederId: 5,
      },
      {
        name: "Butterfly, tropical buckeye",
        dateOfBirth: "1/13/2022",
        description: "Protector",
        profileImage: "http://dummyimage.com/244x100.png/cc0000/ffffff",
        price: 200,
        gender: "Male",
        breederId: 5,
      },
      {
        name: "Asian lion",
        dateOfBirth: "6/15/2022",
        description: "Caring",
        profileImage: "http://dummyimage.com/106x100.png/dddddd/000000",
        price: 2000,
        gender: "Female",
        breederId: 8,
      },
      {
        name: "Blue-faced booby",
        dateOfBirth: "11/17/2021",
        description: "Protector",
        profileImage: "http://dummyimage.com/192x100.png/ff4444/ffffff",
        price: 4000,
        gender: "Male",
        breederId: 2,
      },
      {
        name: "Fox, blue",
        dateOfBirth: "5/19/2022",
        description: "Protector",
        profileImage: "http://dummyimage.com/187x100.png/cc0000/ffffff",
        price: 300,
        gender: "Female",
        breederId: 4,
      },
      {
        name: "Eastern quoll",
        dateOfBirth: "1/29/2022",
        description: "Loving",
        profileImage: "http://dummyimage.com/131x100.png/dddddd/000000",
        price: 2000,
        gender: "Female",
        breederId: 2,
      },
    ],
  });

  const customer = await prisma.Customer.create({
    data: {
      firstName: "John",
      lastName: "Artuz",
      email: "johnartuz@hotmail.com",
      password: "password123",
      phoneNumber: "6475429109",
      address: "test",
      profileImage: "test",
    },
  });

  const petCategory = await prisma.PetCategory.createMany({
    data: [
      {
        pureBreed: false,
        breedName: "Bloodhound",
        categoryName: "Dog",
        petId: 2,
      },
      {
        pureBreed: false,
        breedName: "Labrador",
        categoryName: "Horse",
        petId: 18,
      },
      {
        pureBreed: true,
        breedName: "Rotweiler",
        categoryName: "Chicken",
        petId: 15,
      },
      {
        pureBreed: true,
        breedName: "Boxer",
        categoryName: "Cat",
        petId: 9,
      },
      {
        pureBreed: true,
        breedName: "Boxer",
        categoryName: "Cat",
        petId: 8,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Cat",
        petId: 10,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Cat",
        petId: 20,
      },
      {
        pureBreed: false,
        breedName: "Bloodhound",
        categoryName: "Rabbit",
        petId: 20,
      },
      {
        pureBreed: false,
        breedName: "Poodle Shitzu",
        categoryName: "Horse",
        petId: 4,
      },
      {
        pureBreed: true,
        breedName: "Boxer",
        categoryName: "Turtle",
        petId: 2,
      },
      {
        pureBreed: false,
        breedName: "Poodle Shitzu",
        categoryName: "Horse",
        petId: 5,
      },
      {
        pureBreed: true,
        breedName: "Border Terrier",
        categoryName: "Chicken",
        petId: 18,
      },
      {
        pureBreed: false,
        breedName: "Poodle Shitzu",
        categoryName: "Rabbit",
        petId: 20,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Cat",
        petId: 11,
      },
      {
        pureBreed: true,
        breedName: "Border Terrier",
        categoryName: "Turtle",
        petId: 4,
      },
      {
        pureBreed: true,
        breedName: "Poodle Shitzu",
        categoryName: "Horse",
        petId: 4,
      },
      {
        pureBreed: false,
        breedName: "Boxer",
        categoryName: "Horse",
        petId: 20,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Turtle",
        petId: 14,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Cat",
        petId: 9,
      },
      {
        pureBreed: false,
        breedName: "Poodle Shitzu",
        categoryName: "Dog",
        petId: 8,
      },
      {
        pureBreed: true,
        breedName: "Golden Retriever",
        categoryName: "Turtle",
        petId: 2,
      },
      {
        pureBreed: false,
        breedName: "Labrador",
        categoryName: "Turtle",
        petId: 9,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Horse",
        petId: 20,
      },
      {
        pureBreed: true,
        breedName: "Border Terrier",
        categoryName: "Rabbit",
        petId: 8,
      },
      {
        pureBreed: true,
        breedName: "Rotweiler",
        categoryName: "Chicken",
        petId: 8,
      },
      {
        pureBreed: true,
        breedName: "Labrador",
        categoryName: "Turtle",
        petId: 4,
      },
      {
        pureBreed: false,
        breedName: "Border Terrier",
        categoryName: "Horse",
        petId: 12,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Dog",
        petId: 6,
      },
      {
        pureBreed: false,
        breedName: "Border Terrier",
        categoryName: "Horse",
        petId: 16,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Chicken",
        petId: 16,
      },
      {
        pureBreed: true,
        breedName: "Rotweiler",
        categoryName: "Cat",
        petId: 9,
      },
      {
        pureBreed: false,
        breedName: "Bloodhound",
        categoryName: "Rabbit",
        petId: 16,
      },
      {
        pureBreed: true,
        breedName: "Poodle Shitzu",
        categoryName: "Chicken",
        petId: 9,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Cat",
        petId: 18,
      },
      {
        pureBreed: true,
        breedName: "Bloodhound",
        categoryName: "Rabbit",
        petId: 4,
      },
      {
        pureBreed: false,
        breedName: "Labrador",
        categoryName: "Turtle",
        petId: 6,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Turtle",
        petId: 10,
      },
      {
        pureBreed: false,
        breedName: "Golden Retriever",
        categoryName: "Cat",
        petId: 19,
      },
      {
        pureBreed: false,
        breedName: "Bloodhound",
        categoryName: "Chicken",
        petId: 7,
      },
      {
        pureBreed: false,
        breedName: "Border Terrier",
        categoryName: "Rabbit",
        petId: 7,
      },
      {
        pureBreed: true,
        breedName: "Border Terrier",
        categoryName: "Dog",
        petId: 2,
      },
      {
        pureBreed: false,
        breedName: "Border Terrier",
        categoryName: "Dog",
        petId: 10,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Horse",
        petId: 2,
      },
      {
        pureBreed: true,
        breedName: "Bloodhound",
        categoryName: "Turtle",
        petId: 15,
      },
      {
        pureBreed: true,
        breedName: "Labrador",
        categoryName: "Turtle",
        petId: 19,
      },
      {
        pureBreed: true,
        breedName: "Boxer",
        categoryName: "Cat",
        petId: 14,
      },
      {
        pureBreed: false,
        breedName: "Boxer",
        categoryName: "Rabbit",
        petId: 3,
      },
      {
        pureBreed: true,
        breedName: "Poodle Shitzu",
        categoryName: "Rabbit",
        petId: 16,
      },
      {
        pureBreed: true,
        breedName: "Poodle Shitzu",
        categoryName: "Rabbit",
        petId: 3,
      },
      {
        pureBreed: false,
        breedName: "Rotweiler",
        categoryName: "Horse",
        petId: 16,
      },
    ],
  });

  const sale = await prisma.Sale.createMany({
    data: [
      {
        salesDate: "April 12, 2022",
        breederId: 1,
        customerId: 1,
        petId: 1,
        paymentStatus: "Paid",
        amountPayed: 1000,
        refNumber: 123123,
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
